import 'question.dart';

class QuizBrain {
  int questionNumber = 0;

  List<Question> questionBank = [
    Question(
      'If you call Random.Next( N ) where N = 2, the resulting random values will be either 1 or 1.', //Q
      "false", //A
      ["true", "false"], //O
    ),
    Question(
      'The second expression appearing in the header of a for loop is the _____________, which is a Boolean expression that determines whether the loop will repeat.', //Q
      "test expression", //A
      [
        "test expression",
        "update expression",
        "initialization expression",
        "control expression"
      ], //O
    ),
    Question(
      'The numbers generated by the Random class are ____________calculated by a formula.', //Q
      "pseudorandom numbers", //A
      [
        "pseudorandom numbers",
        "binary encoded numbers",
        "algebraic derivatives",
        "complex variables"
      ], //O
    ),
    Question(
      'A random integer\'s range will begin at zero unless you specify otherwise.', //Q
      "true", //A
      ["true", "false"], //O
    ),
    Question(
      'The ____________ displays a standard Windows Open dialog box.', //Q
      "OpenFileDialog control", //A
      [
        "OpenFileDialog control",
        "Open method",
        "FindFileDialog control",
        "SelectFile control"
      ], //O
    ),
    Question(
      'You can use the StreamWriter class\'s ____________ method to write a line of text to a file.', //Q
      "WriteLine()", //A
      [
        "PrintLine()",
        "WriteText()",
        "WriteLine()",
        "PrintText()",
      ], //O
    ),
    Question(
      'The ____________ displays a standard Windows Save As dialog box.', //Q
      "SaveFileDialog control", //A
      [
        "SaveAs method",
        "SaveFileDialog control",
        "Save_File event",
        "OpenFileDialog control"
      ], //O
    ),
    Question(
      'To append data to an existing file, you open it with the ____________ method.', //Q
      "File.AppendText()", //A
      [
        "File.Append()",
        "File.AppendAll()",
        "File.AppendText()",
        "SelectFile control"
      ], //O
    ),
    Question(
      'Which one of the following statements calls the Jump method of the Animal class using a reference variable named fox?', //Q
      "fox.Jump();", //A
      [
        "Animal.fox.Jump();",
        "Animal(fox) = Jump();",
        "fox.Jump();",
        "fox = new Jump();"
      ], //O
    ),
    Question(
      'To add a new form to a project, first click ____________ on the Visual Studio menu bar, and then select Add Windows Form... from the Project menu.', //Q
      "Project", //A
      [
        "Project",
        "File",
        "Tools",
        "Window",
      ], //O
    ),
    Question(
      'When you add additional forms to a project, you add additional ____________, which are stored in their own source code files.', //Q
      "classes", //A
      ["classes", "objects", "methods", "events,"], //O
    ),
    Question(
      'By using the ____________ access modifier, a class can hide its data from code outside the class.', //Q
      "private", //A
      [
        "public",
        "private",
        "const",
        "ref",
      ], //O
    ),
    Question(
      'The term GUI is short for:____________', //Q
      "Graphical user interface", //A
      [
        "Graphical user interexchange",
        "Graphical unlimited interface",
        "Graphical user interface",
        "Graphical usages interface"
      ], //O
    ),
    Question(
      'the 6 phased cycle used in the process of creating a program is called the____________________', //Q
      "programming development cycle", //A
      [
        "Program Development Process",
        "programming development cycle",
        "programming development process",
        "Programming process of development"
      ], //O
    ),
    Question(
      'What category of user interface preceded GUI\'s?', //Q
      "Command line interface", //A
      [
        "Dark interface",
        "Common interface",
        "Command line interface",
        "Enter only interface"
      ], //O
    ),
    Question(
      'An algorithm is a set of well-defined, ______________ steps that must be taken to perform a task', //Q
      "logical", //A
      [
        "predetermined",
        "obvious",
        "logical",
        "vague",
      ], //O
    ),
    Question(
      'The most commonly used category of interacting with a computer is _________________________', //Q
      "Graphical user interface", //A
      [
        "Command line",
        "Console interface",
        "Graphical user interface",
        "video call face to face"
      ], //O
    ),
    Question(
      'Fake code is another word used for ________________?', //Q
      "pseudocode", //A
      [
        "c# code",
        "incorrect code",
        "pseudocode",
        "irrelevant code",
      ], //O
    ),
    Question(
      'The fifth phase in the process of creating a program is_______________________', //Q
      "Correct syntax errors", //A
      [
        "Understand the program\'s purpose",
        "Design the GUI",
        "Write the program",
        "Correct syntax errors"
      ], //O
    ),
    Question(
      'Controls enhance the functionality of your programs', //Q
      "true", //A
      ["true", "false"], //O
    ),
    Question(
      'Operations performed by an object are found in _____________?', //Q
      "methods", //A
      [
        "The name property",
        "structures",
        "components",
        "methods",
      ], //O
    ),
    Question(
      'The Design of a programs GUI precedes the understanding of a programs purpose', //Q
      "false", //A
      ["true", "false"], //O
    ),
    Question(
      'Each byte is divided into eight smaller storage locations known as ____________.', //Q
      "bits", //A
      [
        "nibbles",
        "pixels",
        "bits",
        "words",
      ], //O
    ),
    Question(
      'Main memory is commonly known as ____________, or RAM.', //Q
      "random-access memory", //A
      [
        "random-access memory",
        "read-append memory",
        "random-asynchronous memory",
        "readily-available memory",
      ], //O
    ),
    Question(
      'Data produced by a computer is sent to a(n) ____________, which formats and presents it.', //Q
      "output device", //A
      [
        "input device",
        "output device",
        "storage device",
        "program",
      ], //O
    ),
    Question(
      'When a piece of data such as 27 or \'North\' is written into a program\'s code, it is called a __________.', //Q
      "literal", //A
      [
        "sentinel",
        "constant",
        "literal",
        "value",
      ], //O
    ),
    Question(
      'To close an application\'s form in code, you use the statement:', //Q
      "this.Close();", //A
      [
        "form.Exit();",
        "me.Quit();",
        "this.Close();",
        "app.Stop();",
      ], //O
    ),
    Question(
      'Fundamental types of data, such as integers and real numbers are known as ____________.', //Q
      "primitive data types", //A
      [
        "fundamental data types",
        "primitive data types",
        "natural data types",
        "basic data types",
      ], //O
    ),
    Question(
      'You can assign a value to a variable only if the value is compatible with the variable\'s ____________.', //Q
      "data type", //A
      [
        "data type",
        "name",
        "scope",
        "lifetime",
      ], //O
    ),
    Question(
      'A numeric literal that is assumed to be an integer is called a(n) ____________.', //Q
      "integer literal", //A
      [
        "real number",
        "integer literal",
        "natural literal",
        "common value",
      ], //O
    ),
    Question(
      'In a try-catch statement, the ____________ keyword appears immediately after the try block.', //Q
      "catch", //A
      [
        "try",
        "catch",
        "break",
        "continue",
      ], //O
    ),
    Question(
      'A ____________ is a identifier for a value that cannot be modified during the program\'s execution.', //Q
      "named constant", //A
      [
        "sentinel",
        "literal",
        "keyword",
        "named constant",
      ], //O
    ),
    Question(
      'Which one of the following statements changes the form\'s BackColor property to Blue?', //Q
      "this.BackColor = Color.Blue;", //A
      [
        "this.Color = Blue;",
        "this.BackColor = Color.Blue;",
        "Form1.BackColor = Blue;",
        "Me.BackColor(Blue);",
      ], //O
    ),
    Question(
      'The ____________ contains statements that can potentially throw an exception.', //Q
      "try block", //A
      [
        "break block",
        "catch block",
        "try block",
        "run block",
      ], //O
    ),
    Question(
      'A(n) ____________ statement has two parts: an if clause and an else clause.', //Q
      "if-else", //A
      [
        "logic",
        "if-else",
        "Boolean",
        "else-if",
      ], //O
    ),
    Question(
      'The ____________ has two possible paths of execution – one path is taken if the Boolean expression is true, and the other path is taken if the Boolean expression is false.', //Q
      "dual-alternative decision structure", //A
      [
        "dual-alternative decision structure",
        "comparative structure",
        "multi-decision structure",
        "branching structure",
      ], //O
    ),
    Question(
      'The ____________ operator is the logical NOT operator, which is a unary operator that takes a Boolean expression as its operand and reverses its logical value.', //Q
      "!", //A
      [
        "<>",
        "!",
        "&&",
        "||",
      ], //O
    ),
    Question(
      'The ____________ method can be used to determine whether one string is greater than or less than another string.', //Q
      "String.Compare", //A
      [
        "String.Equals",
        "String.Compare",
        "String.IsGreater",
        "String.String",
      ], //O
    ),
    Question(
      'Once you create a ListBox control, you add items you wish to display to its ____________.', //Q
      "Items property", //A
      [
        "Display property",
        "Text property",
        "Items property",
        "Values property",
      ], //O
    ),
    Question(
      'When the user selects an item in a ListBox, the item is stored in the ListBox\'s ____________ property.', //Q
      "SelectedItem", //A
      [
        "Checked",
        "SelectedValue",
        "DataSelection",
        "SelectedItem",
      ], //O
    ),
    Question(
      'When the user selects an item in a ListBox, the item\'s index is stored in the Listbox\'s ____________ property.', //Q
      "SelectedIndex", //A
      [
        "DataValue",
        "SelectedIndex",
        "Index",
        "ValueIndex",
      ], //O
    ),
    Question(
      'A parameter variable\'s scope is the ____________ in which the parameter variable is declared.', //Q
      "method", //A
      [
        "namespace",
        "class",
        "field",
        "method",
      ], //O
    ),
    Question(
      'When an argument is ____________, only a copy of the argument\'s value is passed into the parameter variable.', //Q
      "passed by value", //A
      [
        "passed by reference",
        "passed by value",
        "named",
        "uninitialized",
      ], //O
    ),
    Question(
      'When you pass an argument to a method, the argument\'s data type must be ____________ with the receiving parameter\'s data type.', //Q
      "assignment compatible", //A
      [
        "assignment compatible",
        "user friendly",
        "data bound",
        "identical to",
      ], //O
    ),
    Question(
      'The ____________ is a collection of statements that are performed when a method is executed.', //Q
      "method body", //A
      [
        "method body",
        "executable code",
        "method header",
        "method code listing",
      ], //O
    ),
    Question(
      'In C#, you declare a reference parameter by writing the ____________ keyword before the parameter variable\'s data type.', //Q
      "ref", //A
      [
        "const",
        "ref",
        "out",
        "private",
      ], //O
    ),
    Question(
      'Which of the following data types can be returned from a method?', //Q
      "any of these", //A
      [
        "int",
        "bool",
        "string",
        "any of these",
      ], //O
    ),
    Question(
      'When a ____________ finishes, it returns a value to the statement that called it.', //Q
      "value-returning method", //A
      [
        "public method",
        "value-returning method",
        "void method",
        "private method",
      ], //O
    ),
    Question(
      'In C#, you declare an output parameter by writing the ____________ keyword before the parameter variable\'s data type.', //Q
      "out", //A
      [
        "public",
        "ref",
        "const",
        "out",
      ], //O
    ),
  ];

  bool getStatus() {
    if (questionNumber == questionBank.length - 1 ||
        questionNumber > questionBank.length - 1) {
      return true;
    } else {
      return false;
    }
  }

  void nextQuestion() {
    if (questionNumber < questionBank.length - 1) {
      questionNumber++;
    }
  }

  String getQuestionText() {
    return questionBank[questionNumber].questionText;
  }

  String getCorrectAnswer() {
    return questionBank[questionNumber].questionAnswer;
  }

  void reset() {
    questionNumber = -1;
  }
}
